### PR TITLE
edit appointment implementation

### PR DESCRIPTION
**Pull request by simbayippy**
will do merge conflicts directly in github

### CODE REVIEW

**Comment by simbayippy** [comment]
ignore this PR first, its PR-ing my bin files

**Comment by simbayippy** [comment]
> ignore this PR first, its PR-ing my bin files

done, can check and merge now

**Comment by simbayippy** [comment]
checks failing here due to Person constructor not having the fields of age/gender/ethnicicity. Added it and merged into main so checks will (pass)/ fail due to other reasons after merging this PR into main

**Review by Bryan-Goh — APPROVED** [review]
Looks good to me

**Review by Bryan-Goh — DISMISSED** [review]
When i try to run it there is an error with the Person class saying that gender was not initialized correctly

**Comment by simbayippy** [comment]
> checks failing here due to Person constructor not having the fields of age/gender/ethnicicity. Added it and merged into main so checks will (pass)/ fail due to other reasons after merging this PR into main

@Bryan-Goh

**Pull request merged**
